config/routes.rb
Rails.application.routes.draw do
  get '', to: 'sessions#new'

  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :feeds do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feed.rb
class Feed < ApplicationRecord
  mount_uploader :image, ImageUploader
   belongs_to :user
   validates :image, presence: true
   validates :content, length: { in: 1..140 }
 end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
   validates :email, presence: true, length: { maximum: 255 },
                     format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                     uniqueness: true
   before_validation { email.downcase! }
   has_secure_password
   validates :password, presence: true, length: { minimum: 6 }

   has_many :feeds
 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
   include SessionsHelper
 end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]

  def index
    @feeds = Feed.all.order("id DESC")
  end
  def show
  end
  def new
    if params[:back]
      @feed = Feed.new(feed_params)
    else
      @feed = Feed.new
    end
  end

  def confirm
    @feed = current_user.feeds.build(feed_params)
    render :new if @feed.invalid?
  end

  def edit
  end
  def create
    @feed = current_user.feeds.build(feed_params)

    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'create post sucess' }
        format.json { render :show, status: :created, location: @feed }
      else
        format.html { render :new }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end
 def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'edit post sucess' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: 'delete post sucess.' }
      format.json { head :no_content }
    end
  end

  private
    def set_feed
      @feed = Feed.find(params[:id])
    end
    def feed_params
      params.require(:feed).permit(:image, :image_cache, :user_id, :content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'Login fail'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'Logout!'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    if logged_in?
      @user = User.find(params[:id])
    else
      flash[:notice] = 'create login'
      redirect_to new_session_path
    end
  end
  private
   def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/feeds_helper.rb
module FeedsHelper
  def choose_new_or_edit
    if action_name == "new" || action_name == "cofirm" || action_name == "create"
      confirm_feeds_path
    elsif action_name == "edit"
      feed_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/feeds/_form.html.erb
<div class="new_feed_container">
  <%= form_with(model: feed, local: true, url: choose_new_or_edit) do |form| %>
    <% if feed.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

        <ul>
        <% feed.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
      <p>content：</p>
      <p><%= form.text_area :content, size: "80x10" %></p>
      <p>photo：</p>
      <p><%= form.file_field :image %></p>
      <p><%= image_tag(@feed.image.url) if @feed.image && @feed.image.url %></p>
      <%= form.hidden_field :image_cache %>
      <%= form.hidden_field :user_id %>
      <div class="actions">
        <%= form.submit "create Image" %>
      </div>
  <% end %>
</div>

app/views/feeds/confirm.html.erb
<h1>Confirmation Screen</h1>
<%= form_with(model: @feed, url: feeds_path, local: true) do |form| %>
  <!-- 確認画面でアップロードした画像を表示させるための記述 -->
  <%= image_tag(@feed.image.url) if @feed.image && @feed.image.url %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>
  <p>Content:<%= @feed.content %></p>
  <%= form.submit "To post" %>
<% end %>
<%= form_with(model:@feed, url:new_feed_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>
  <%= form.submit "Return", name: "back" %>
<% end %>

app/views/feeds/edit.html.erb
<div class="main-container">
  <div class="index_container">
    <h3>edit screen</h3>
 <%= render 'form', feed: @feed %>
<button type="button" class="btn btn-primary btn-sm">  <%= link_to 'Show', @feed %> </button>
  <button type="button" class="btn btn-primary btn-sm">  <%= link_to 'Back', feeds_path %></button>
  </div>
</div

app/views/feeds/index.html.erb
<div class="main-container">
  <div class="index_container">
    <ul>
      <li><h1>Post List</h1></li>
    </ul>
    <% @feeds.each do |feed| %>
      <div class="feed">
        <div class="feed-top">
          <%= feed.user.name %>
          <div class="btn-group dropdown">
         <div class="dropdown-menu">
              <p class="dropdown-item"><%= link_to 'confirm screen', feed, class:"dropdown-item"%></p>
              <p class="dropdown-item"><%= link_to 'edit post', edit_feed_path(feed), class:"dropdown-item" %></p>
              <p class="dropdown-item"><%= link_to 'delete post', feed, method: :delete, data: { confirm: 'Are you sure?' }, class:"dropdown-item" %></p>
            </div>
          </div>
        </div>
        <p id="content"><%= feed.content %></p>
        <p id="image"><%= image_tag feed.image.url %></p>
   </div>
    <% end %>
  </div>
</div>

app/views/feeds/new.html.erb
<div class="main-container">
  <h3>New post</h3>

  <%= render 'form', feed: @feed %><%# 変数@feedを feedという変数に移して、render先のページに持っていくことができる %>

  <%= link_to 'Back', feeds_path %>
</div>

app/views/feeds/show.html.erb
<div class="main-container">
    <p><strong>User:<%= @feed.user.name %></strong></p>
      <p><strong>Contents：<%= @feed.content %></strong></p>
      <p><strong>Image:</strong></p>
        <%= image_tag @feed.image.url %>
  <button type="button" class="btn btn-primary btn-sm"><%= link_to 'Edit', edit_feed_path(@feed) %> </button>
  <button type="button" class="btn btn-primary btn-sm">  <%= link_to 'Back', feeds_path %></button>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Facebook Clone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
 <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="row header-row">
            <div class="col-md-8 col-md-offset-2">
              <a class="navbar-brand" id="nav-content">FaceBookClone</a>
              <% if logged_in? %>
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navi">
                  <span class="sr-only">FaceBookClone</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <div id="gnavi" class="collapse navbar-collapse" >
                  <ul class="nav navbar-nav">
                    <li><%= link_to "profile", user_path(current_user.id) ,id:"nav-content"%></li>
                    <li><%= link_to "login account", session_path(current_user.id), method: :delete ,id:"nav-content"%></li>
                    <li><%= link_to 'Post List', feeds_path ,id:"nav-content"%></li>
                    <li><%= link_to 'New Post and Image', new_feed_path ,id:"nav-content"%></li>
                  </ul>
                </div>
              <% else %>
                <div id="gnavi">
                  <ul class="nav navbar-nav">
                    <li><%= link_to "User register", new_user_path ,id:"nav-content"%></li>
                    <li><%= link_to "Login", new_session_path ,id:"nav-content"%></li>
                  </ul>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <% flash.each do |key, value| %>
        <div class="container-fluid">
          <div class="row" id="notice-row">
            <div class="col-md-8 col-md-offset-2">
                <%= content_tag(:div, value, id: "#{key}") %>
            </div>
          </div>
        </div>
      <% end %>
      <%= yield %>
      <footer>
        <p>運営会社  FacebookClone Company</p>
        <p>© 2020-2021 Copyright FacebookClone Company.</p>
      </footer>
    </main>
  </body>
</html>

app/views/users/new.html.erb
<div class="user-container">
  <h1>User Register</h1>
  <% if @user.errors.any? %>
    <div class="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="user-form">
    <%= form_with(model: @user, local:true) do |f| %>
      <%= f.label :name, "Name" %>
      <%= f.text_field :name %>
      <%= f.label :email, "Mail address" %>
      <%= f.email_field :email %>
      <%= f.label :password, "Password" %>
      <%= f.password_field :password %>
      <%= f.label :password_confirmation, "password_confirmation" %>
      <%= f.password_field :password_confirmation %>
      <p><%= f.submit "create new user" %></p>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h2><%= @user.name %>Page</h2>
<p>mail address：<%= @user.email %></p>
<%= link_to "Picture Index", feeds_path %>